spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    generate-ddl: true

  kafka:
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        isolation.level: read_committed
    listener:
      type: batch
server:
  port: 8081


