spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
